name: Deploy website
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types: [opened, edited]
    branches: # these filters are for the branch that is targeted for a pull request
      - main
      - dev
      - 'dev-*' # dev-new dev-this-is-new
      - 'feat/**' # feat/new feate/new/button
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules #~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: lint and testing
        id: run-tests
        run: |
          npm run lint
          npm run test
      - name: upload test reports
        if: failure() && steps.run-tests.outcome == 'failure' #${{  }}
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules #~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: build
        run: npm run build
      - name: Publish JS file Name
        id: publish
        run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: |
            dist
            package.json
  deploy:
    needs: build
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files #the same name as upload artifacts
      - name: output contents
        run: ls
      - name: output file name
        run: echo "${{needs.build.outputs.script-file}}"
      - name: Deploy
        run: echo "Deploying..."
  deploy-reuse:
    needs: build
    uses: ./.github/workflows/reusable.yml
    with:
      artifact-name: dist-files
    #secrets:
    #some-secret: ${{secrets.some-secret}}
  print-deploy-result:
    needs: deploy-reuse
    runs-on: ubuntu-latest
    steps:
      -name: print deploy output
      run: echo "${{needs.deploy-reuse.outputs.result}}"
  report:
    if: failure()
    needs: [test, build, deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "something went wrong"
          echo "${{github}}"
